// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/contacts': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contacts').default>>>>
    }
    '/slop': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/slop').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.bun/@nuxt+nitro-server@3.21.2+009aa0051d531bf9/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}